# Generated by Django 2.2.3 on 2019-07-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0002_auto_20190705_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='brand',
        ),
        migrations.AddField(
            model_name='order',
            name='brand',
            field=models.ManyToManyField(to='new.Brands'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='marketing',
        ),
        migrations.AddField(
            model_name='order',
            name='marketing',
            field=models.ManyToManyField(to='new.Marketing'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='sait',
        ),
        migrations.AddField(
            model_name='order',
            name='sait',
            field=models.ManyToManyField(to='new.Saits'),
        ),
    ]
