# Generated by Django 2.2.3 on 2019-07-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0003_auto_20190705_0207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brief',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name_company', models.CharField(max_length=255)),
                ('contact_info_name', models.CharField(max_length=255)),
                ('contact_adress', models.CharField(max_length=255)),
                ('contact_data_project', models.CharField(max_length=255)),
                ('contact_were_see_us', models.CharField(max_length=255)),
                ('contact_bissnes', models.CharField(max_length=255)),
                ('contact_brend', models.CharField(max_length=255)),
                ('contact_brend_perfect', models.CharField(max_length=255)),
                ('contact_what_do', models.CharField(max_length=255)),
                ('contact_marketing', models.CharField(max_length=255)),
                ('contact_problem', models.CharField(max_length=255)),
                ('contact_people', models.CharField(max_length=255)),
                ('contact_concurents', models.CharField(max_length=255)),
                ('contact_money', models.CharField(max_length=255)),
                ('contact_menu_site', models.CharField(max_length=255)),
                ('contact_servisess_site', models.CharField(max_length=255)),
                ('contact_update_site', models.CharField(max_length=255)),
                ('contact_risk_site', models.CharField(max_length=255)),
                ('contact_mean_update', models.CharField(max_length=255)),
                ('contact_site_list', models.CharField(max_length=255)),
                ('contact_not_site_list', models.CharField(max_length=255)),
                ('contact_new_site', models.CharField(max_length=255)),
                ('contact_strategy', models.CharField(max_length=255)),
                ('contact_site_strategy', models.CharField(max_length=255)),
                ('contact_site_reclam', models.CharField(max_length=255)),
                ('contact_site_seo', models.CharField(max_length=255)),
                ('contact_site_social', models.CharField(max_length=255)),
                ('contact_more_info', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='brand',
            field=models.ManyToManyField(blank=True, to='new.Brands'),
        ),
        migrations.AlterField(
            model_name='order',
            name='marketing',
            field=models.ManyToManyField(blank=True, to='new.Marketing'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sait',
            field=models.ManyToManyField(blank=True, to='new.Saits'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subject',
            field=models.TextField(blank=True, verbose_name='Собщение'),
        ),
    ]
