# Generated by Django 2.2.3 on 2019-07-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0004_auto_20190705_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ваше имя')),
                ('body', models.CharField(blank=True, max_length=255, verbose_name='Ваше телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Ваше email')),
                ('subject', models.TextField(blank=True, verbose_name='Собщение')),
            ],
        ),
    ]
